### ISSUE TITLE
Running 'meteor-cordova-splash' returns error 'command not found'

### ISSUE THREAD

**Issue by adammoisa** [emilbryggare/meteor-cordova-splash#1]
Steps: 
- brew install imagemagick  --> successful 
- npm install meteor-cordova-splash -g  --> successful
- meteor-cordova-splash --> -bash: meteor-cordova-splash: command not found

I used your meteor-cordova-icon and it worked just fine.

**Comment by emilbryggare** [comment]
@adammoisa:
The following worked for me on a new MacOS Sierra installation.
```
npm install meteor-cordova-splash -g
brew install imagemagick
meteor-cordova-splash
```

Are you sure the installation went ok?
